# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec4fff11a85c996d200b310be251d1705f8b45e7dacb4c2a80818defc2741407de4406ab902b78cb27744f002ecba2709c4355814ad578ec62f0d89d8cbc377e

test:
  secret_key_base: 8ffb56d68b7466591206599332c3aa0bbd43ccc6df7a3cbffa98c45e8f2939a3dcbc4e11208e7b1e35f22403b8a4ac3ba4e14d82d6dfc00e85fb323afd2e863d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
